### ISSUE TITLE
Global Namespace Pollution

### ISSUE THREAD

**Issue by GordonSmith** [observablehq/runtime#241] opened 2020-03-31 05:42 UTC
I suspect this is being pulled in by d3-require, but `window.define` gets overwritten even if it existed prior to loading this library:  https://github.com/d3/d3-require/blob/master/src/index.js#L88

**Comment by mbostock** [comment] 2020-03-31 17:50
That’s correct. Unfortunately this is not something we can fix because it’s how [AMD](https://requirejs.org/docs/whyamd.html) works: the global define is needed so that when require’d modules load asynchronously, they can register themselves with the AMD loader.

**Comment by mbostock** [comment] 2020-03-31 17:50
Duplicate of d3/d3-require#33.

**Closed by mbostock** 2020-03-31 17:50 UTC

**Comment by GordonSmith** [comment] 2020-03-31 17:54
@mbostock This is bit of a shame as it prevents the embedding of download notebooks in third party web sites...

**Comment by mbostock** [comment] 2020-03-31 21:55
@GordonSmith It only applies if you call require, in which case you’ll need the global define or the notebook will be broken, anyway. If you don’t call require, the global define won’t be set.

**Comment by GordonSmith** [comment] 2020-04-01 06:38
Unfortunately that is any notebook which contains some markdown as the stdlib `requires` the  markdown js library,..

IOW embedding any notebook which contains markdown will overwrite the previously declared global define, potentially causing pain  for the hosting website.

To be fair AMD require implementations have been battling this issue forever...

**Comment by mootari** [comment] 2020-04-01 07:44
@GordonSmith I recommend moving the discussion to https://talk.observablehq.com/, where others with practical experience wrt embedding might be able to assist you.

As an aside, you could try to define get/set callbacks for `window.define` ([here](https://observablehq.com/@mootari/codepens-in-observable) are some examples for scope wrapping and object proxying).
