### ISSUE TITLE
Getting the value of a variable with no ID.

### ISSUE THREAD

**Issue by GordonSmith** [observablehq/runtime#248] opened 2020-04-27 16:03 UTC
I don't believe there is any sane way to get the value of a variable which does not have an ID?

At the moment the API is:
* module(id).value()

Would it be possible to add a 
* variable.value()

Method as well?

Why?  This will help to keep the VS Code Editor values in sync with the live page values (without adding an extra Inspector callback hook).

![image](https://user-images.githubusercontent.com/966863/80393791-e4a31e00-88a8-11ea-87a7-f692b51520ca.png)

**Comment by mbostock** [comment] 2021-01-18 00:25
There isn’t currently a supported way of doing this, somewhat by design. (We can make stronger assumptions about code being unreachable if unnamed variables cannot be inspected.) That said, we might reconsider this design in the future. There has been internal discussion around using names such as `$1`, `$2`, etc. to refer to cells by their automatic identifier rather than names. However, we have no immediate plans to implement this, so I’m closing this issue for now.

**Closed by mbostock** 2021-01-18 00:25 UTC
